### ISSUE TITLE
Recommended way of plotting

### ISSUE THREAD

**Issue by mbhall88** [rpetit3/fastq-scan#3]
I was wondering if you usually plot the output of `fastq-scan`? If so, do you have a standardised way of doing this?

I can whip something up in python of course, but I thought I would check first whether you had anything handy?

**Comment by rpetit3** [comment]
Hi @mbhall88! Apologies for the delay! 

I don't at the moment. I've only used it with High Charts (ex. https://staphopia.emory.edu/sample/94/).
