### ISSUE TITLE
Warning: missing quality for a read

### ISSUE THREAD

**Issue by hayleyjaywilson** [rpetit3/fastq-scan#5]
Hello,
I am getting the following error on any fastq I try to scan - this includes ones produced by different institutions and timeframes so i don't think it is a batch problem.
`cat SRR13790218_subreads.fastq.gz | fastq-scan -g 2250000
WARNING: Missing quality for a read.
n??
`h?n????4L????$???K?)?Ƈ(??v?'sϮ/47??O???'?b(????FTڛ`?U?y
??z?d"F????M-i?V?v?                                     ?:3/?`
                   {{????9
                          	??h??-u??'gq5?G-(?d?	?^APЉ˴@? ƖgؾR???N?QR8܈?ť?\?	?q?X
                                                                                            ??
                                                                                              ?m?g?4?JV???V&?Hx?n?;3?{F?׈¤2gB?>ڈ??
?0?x??Mtm?FND??Z??????????߱??X?d9?Du?Ӝ????8?5?3{?⊳/?G#??d@?L?????'?7r??O??D?$J>-T	????{?\qW???
                                                                                                    ??6̑M?߀?Y??X?l???>0r?;??yz?#???Ԋ?Y1/[)?_}?;?et?Z????]??_??eM?????3??CR
                                                                                                                                                                         6?z6?????;?y?????j?z?K?5?jcO6?X??G??$?H`?????2?O???*?̛??L??Hl;?D?zX?????qb?s

???j?Vp??#?X*??x???

Please fix it to continue.`

I am not sure what I need to do to fix this? I haven't had an issue using the fastqs for other applications so I don't think there is a problem with the file?
Thanks

**Comment by rpetit3** [comment]
Hi @hayleyjaywilson !

Looks like you figured it out, but incase for others,fastq-scan doesn't support gzip inputs, so you just have to `zcat` them and pipe into fastq-scan.

Please feel free to let me know if I can help wioth anything!
Robert

**Comment by hayleyjaywilson** [comment]
Hi Robert,

Thanks for the reply. Yes - I realised I hadn't unzipped the files! I tried to delete the issue so as not to send unneeded ones but never mind.
Thanks for a great tool!

Hayley
________________________________
